
-- Étape 6 : REVOKE EXECUTE FROM anon sur les fonctions SECURITY DEFINER non publiques
-- Aucune modification de logique. Allowlist publique préservée.

REVOKE EXECUTE ON FUNCTION public.add_default_sav_statuses_to_new_shop() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.add_default_sav_types_to_new_shop() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_add_sms_credits(uuid, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_remove_sms_credits(uuid, integer) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_reset_all_monthly_sms() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.admin_reset_shop_monthly_sms(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.after_inventory_item_change() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.apply_inventory_session(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.audit_part_reservations(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.begin_inventory_session(text, text, text, uuid[]) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.begin_inventory_session(text, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.calculate_invoice_amounts() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.calculate_shop_storage_usage(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.check_subscription_limits(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.check_subscription_limits_v2(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.check_subscription_limits_v3(uuid, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.cleanup_sav_delay_notifications() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.clear_security_codes_on_completion() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.convert_accepted_quote_to_customer() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.copy_default_role_permissions() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_profile_only(text, text, text, text, user_role, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_real_user_for_shop(text, text, text, text, text, user_role, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_user_for_shop(text, text, text, text, text, user_role, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.create_user_with_profile(text, text, text, text, text, user_role, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.ensure_non_negative_time_minutes() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.ensure_super_admin_profile() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.execute_custom_widget_query(text, uuid, text, text, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.find_or_create_tracked_product(uuid, text, text, text, text, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_invoice_number(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_satisfaction_token() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_shop_slug(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.generate_tracking_slug(text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_all_shops_storage_usage() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_parts_statistics(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_sav_visit_counts(uuid[]) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_sms_credits_breakdown(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.get_total_sms_credits(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_sav_completion_stock() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_sav_part_stock_reservation() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.invite_user_to_shop(text, text, text, text, user_role, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.list_ghost_reserved_parts(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.list_savs_for_ghost_reserved_parts(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.normalize_customer_name() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.prevent_negative_part_quantity() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.recalculate_inventory_session_totals(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.recalculate_part_reservations(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.release_part_reservations_on_final_status() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.reset_monthly_counters() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.reset_monthly_sms_credits() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sav_cases_attach_tracked_product() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sav_cases_refresh_tracked_product_counters() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_inventory_item_count(uuid, uuid, integer, text, text, text) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_shop_slug() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.set_tracking_slug() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_loaner_equipment_status() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_part_updates_to_sav() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.sync_sms_credits_after_purchase() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_custom_widgets_updated_at() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_message_read_status() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_part_price_timestamp() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_sav_case_details_timestamp() FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.update_support_message_read_status() FROM anon, public;
